ci: update versions on stable branch
The maven action plugin used to only be able to update the version on the default branch of the repository. Recently a change has been made to make the branch configurable. For this reason a step has been introduced to the workflow to decide our git branch.

It works by first figuring out what the major and minor version of the release are (e.g. 1.4 when the release is 1.4.1). If this fails to yield a result we exit the workflow. Otherwise we will add the branch (stable/major.minor) as an output of this step. This will then be used by the community-action-maven-release as the branch for updating the versions.

diff --git a/.github/workflows/deploy-artifact.yml b/.github/workflows/deploy-artifact.yml
--- a/.github/workflows/deploy-artifact.yml
+++ b/.github/workflows/deploy-artifact.yml
@@ -108,13 +108,33 @@ jobs:
           gpg_private_key: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC }}
           passphrase: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
 
+      # We want the community-action-maven-release to update the versions on the correct branch. For
+      # this reason an extra step is introduced to decide what branch we should pass to this action.
+      # In the case of a push to the main branch, or an alpha release we should update the main branch.
+      # In other cases a stable/major.minor branch should be available. In this step we first find
+      # the major and minor versions of this tag. If we found them we will set the BRANCH env variable
+      # to stable/major.minor.
+      - name: Decide git branch
+        id: branch
+        if: github.ref != 'refs/head/main'
+        run: |
+          if [[ ${{ github.event.release.tag_name }} != *"alpha"* ]]; then
+            MAJOR_MINOR_VERSION=$(echo ${{ github.event.release.tag_name }} | sed -rn 's/^([0-9]+.[0-9]+).[0-9]+.*$/\1/p')
+            test -z "${MAJOR_MINOR_VERSION}" && echo "::error::Tag ${{ github.event.release.tag_name }} does not adhere to semantic versioning" && exit 1
+            echo "::set-output name=branch::stable/$MAJOR_MINOR_VERSION"
+            echo "Branch = stable/$MAJOR_MINOR_VERSION"
+          else
+            echo "::set-output name=branch::${{ github.event.repository.default_branch }}"
+            echo "Branch = ${{ github.event.repository.default_branch }}"
+          fi
+
         # In extension-testcontainer we have a config file which contains the image tag. This is managed by maven and
         # maven will set this to the project version in this step, unless the placeholder (${project.version}) has been
         # overridden by the "Update tag in config" step. This happens when the workflow is triggered by a change on the
         # main branch.
       - name: Build and deploy to Maven
         id: release
-        uses: camunda-community-hub/community-action-maven-release@v1.0.12
+        uses: camunda-community-hub/community-action-maven-release@v1
         with:
           release-version: ${{ github.event.release.tag_name }}
           release-profile: community-action-maven-release
@@ -125,6 +145,7 @@ jobs:
           maven-gpg-passphrase: ${{ steps.secrets.outputs.MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE }}
           maven-url: s01.oss.sonatype.org
           github-token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ steps.branch.outputs.branch }}
 
       - name: Attach artifacts to GitHub Release (Release only)
         if: github.event.release
